### PR TITLE
Extend order info to all transactions

### PR DESCRIPTION
**Pull request by valentino-sm**
1.  Fix brief order view from user.
2.  Save order_info to worker.
3.  Save worker.order_info in __order_transaction to db instead of empty row.
4.  Show order_info in full order view for admin.
5.  Hide notes if empty.

Don't use if you are not sure what you are doing.

### CODE REVIEW

**Comment by valentino-sm** [comment]
1. Operator And is never executes. Do you have reasons for
2. Should be saved to db. Another option is loading from last transaction when worker starts

**Comment by valentino-sm** [comment]
2. Probably we should extend db.users for order_info. Another option is loading from last transaction when worker starts

**Review by Steffo99 — COMMENTED** [review]
While this is a clever idea (I never thought about storing state variables in the worker class while developing greed!), I don't really see the need to add order_info to purchase transactions, as it would be redundant and possibly inaccurate...

I'm not sure about this PR :thinking:

**Comment by valentino-sm** [comment]
I know this is some kind of hack but I just need the way to view order_info in-app admin-orders directly without looking into transactions.

**Comment by Steffo99** [comment]
I think I won't merge this, as it's a bit of an hack, but I'll keep your branch, since it's a good reference for implementing that feature :)

Thanks for the contribution anyways!

**Pull request closed without merging**
