### PR TITLE
Bitcoin payments

### PR DESCRIPTION
**Pull request by DarrenWestwood**
### Integrating Bitcoin
1) If you plan on accepting Bitcoin payments, enter your Blockonomics api key into the config.ini file:
https://www.blockonomics.co/merchants#/

2) In order to receive notifications of Bitcoin payments, you are required to deploy your bot in order to receive a public url where webhooks can be delivered to Greed Bot.

For **testing** ngrok https://ngrok.com/download works well:
- Run the following command in a new terminal:`./ngrok http 5000`
- Look at the "Forwarding" line to see your unique Ngrok domain name eg. `https://greed.ngrok.io/`

For **production** gunicorn can be used https://pypi.org/project/gunicorn:
- Run the following command to launch Greed Bot: `gunicorn --workers=1 core:app` or add `web: gunicorn --workers=1 core:app` to your Procfile
Once Greed Bot is running and you have received your public url eg. `https://greed.herokuapp.com/`

**Callback URL**
- Add `callback?secret=YOUR_SECRET_HERE_` to the end of your URL. eg. `https://greed.herokuapp.com/callback?secret=YOUR_SECRET_HERE_`, replacing with the secret entered in your config.ini file.
- Set this url as the HTTP Callback URL in your Blockonomics account:
https://www.blockonomics.co/merchants#/page3

### CODE REVIEW

**Comment by Steffo99** [comment]
Woah! You made a lot of stuff!

Sadly, I won't be able to review this until I am done with my exams 😅 , so it may take a while...

Please be patient, and thanks! 😄

**Comment by Steffo99** [comment]
By the way, are you affiliated with Blockonomics?

**Comment by DarrenWestwood** [comment]
> Please be patient, and thanks!

Thanks looking forward to your feedback when you have the time. I will reopen the pull-request for you to have a look and comment on.



> By the way, are you affiliated with Blockonomics?

Yes, I'm a developer for Blockonomics.

**Comment by DarrenWestwood** [comment]
I have opened a new pull-request with modified instructions.
https://github.com/Steffo99/greed/pull/31

**Comment by GuyFawkesII** [comment]
Hello , I love this bitcoin payment feature
Can I set it up on a own VPS instead of herokupapp?

**Comment by DarrenWestwood** [comment]
> Hello , I love this bitcoin payment feature , thanks

Please note the features request has been moved here: #31

> will the order going to be placed even if the payment is unconfirmed or it's necessary that a payment confirmation should be done before the order is placed and the owner gets a notification from greed about the order ?

In the testing websocket version orders are accepted instantly (0 confirmations). 
In production, we recommend waiting for the payment to confirm via callback (2 confirmations).

This ensures payments are fully confirmed to your wallet before credit is funded. (This will happen anytime in the background, and notify the user)

**Pull request closed without merging**
